# Generated by Django 4.2.9 on 2026-03-29 20:31

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/", validators=[store.models.validate_image_size]
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_thumbnail",
            field=models.BooleanField(
                default=False, help_text="Use this image as the product card thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower number shows first"
            ),
        ),
    ]
